### ISSUE TITLE
Include GOAT (Pre-Errata) card

### ISSUE THREAD

**Issue by tin-pham** [NiiMiyo/EDOPro-Hd-Downloader#11]
I already did /all download, it not download pre-errata card

**Comment by NiiMiyo** [comment]
@tin-pham Sorry for the late reply.

All images are downloaded from [YGOProDeck](https://ygoprodeck.com)'s API. It's possible that their API doesn't store multiple versions of cards, as I was unable to access a different version of [Ancient Fairy Dragon](https://ygoprodeck.com/card/ancient-fairy-dragon-2229) through their website and [searching for it on the API](https://db.ygoprodeck.com/api/v7/cardinfo.php?fname=Ancient%20Fairy%20Dragon) also seems to have only 1 entry for this card (which actually seems to be the pre-errata version of the card).

This means that it wouldn't be possible to add different versions of the cards without configuring each card to a different image that is not provided by [YGOProDeck](https://ygoprodeck.com)'s API, which is too much effort for a not good enough reward.

That being said, you are still able to find a higher resolution image (searching the web or making it yourself) and put it in the `/pics` folder of your EDOPro installation with the right ID.
