### ISSUE TITLE
"Stuck" in download

### ISSUE THREAD

**Issue by Jack6591** [NiiMiyo/EDOPro-Hd-Downloader#14]
Arrived at 49.48% the download of the cards (run with /allcards) stopped and doesn't seem to restart, if I close the promp I guess I have to download them again right?

**Comment by NiiMiyo** [comment]
@Jack6591

Sorry for the late reply. I'm not sure why it stopped downloading, but you can close the prompt and it will continue downloading where it stopped. But I believe that by now you probably already figured that out.

**Comment by Jack6591** [comment]
No problem, yes I eventually opted for a "reboot" and it went smoothly....
