### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by DrSchiggy** [NiiMiyo/EDOPro-Hd-Downloader#4]
Can't download the hd-cards: Http Error 403.

**Comment by Jlytsman** [comment]
+1

**Comment by elrod829** [comment]
+1

**Comment by NiiMiyo** [comment]
Seems that YGOPRODECK changed the URL to the images and this is causing the error.
I'm short of time right now, but I will fix it as soon as possible.

**Comment by NiiMiyo** [comment]
Solved on [release v2.1](https://github.com/NiiMiyo/EDOPro-Hd-Downloader/releases/tag/2.1)
