### ISSUE TITLE
Would this program overwrite existing images if their ID is not specified in the tracker?

### ISSUE THREAD

**Issue by ExLuck6** [NiiMiyo/EDOPro-Hd-Downloader#7]
So for example, I have a bunch of images that are low quality.
would this program overwrite the old low quality images and replace them with the higher quality images IF they weren't being protected by the tracker file?
Cuz if yes, that would be cool, won't have to track down the low quality images to delete.

**Comment by NiiMiyo** [comment]
Yes, if the image already exists and it's not on the tracker it gets overwrited, be it bigger or lower quality.

**Comment by ExLuck6** [comment]
> Yes, if the image already exists and it's not on the tracker it gets overwrited, be it bigger or lower quality.

awesome, thank you so much! and thank you a ton for making this program!!
